### ISSUE TITLE
No error message is surfaced when user attempts to use m-* commands offline

### ISSUE THREAD

**Issue by Xenonym** [CS2103AUG2017-W09-B3/main#93]
To reproduce: perform `m-*` commands offline. The program will report success but no changes will occur.

**Comment by dalessr** [comment]
Thank you for your suggestion!

We actually considered this before. However, if we add in functions for checking the network connection, it will check every time when the app launches. Thus, the user cannot even use offline commands since they cannot open the app without the internet. Therefore, we decide to leave it first.

We will try to figure out how to check the network connection when it requests to load a webpage :)
Thanks again!
